name: Daily Tech Fact Generator

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  generate-tech-fact:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Generate Tech Fact
      id: tech-fact
      run: |
        python << EOF
        import requests
        import random
        from datetime import datetime, timedelta

        # List of technology facts (you can expand this)
        tech_facts = [
            "The first computer bug was an actual bug - a moth trapped in a relay of the Harvard Mark II computer in 1947.",
            "More than 6,000 new computer viruses are created and spread every month.",
            "The first computer mouse was made of wood in 1964.",
            "Around 90% of the world's currency is digital, existing only on computers.",
            "The QWERTY keyboard layout was designed to slow down typing to prevent typewriter jams."
        ]
        
        # Select a random fact
        fact = random.choice(tech_facts)
        
        # Generate filename with today's date
        today = datetime.now().strftime("%Y-%m-%d")
        filename = f"_posts/{today}-daily-tech-fact.md"
        
        # Write the fact to a new post
        with open(filename, 'w') as f:
            f.write(f'''---
layout: default
title: "Daily Tech Fact - {today}"
date: {today}
---

{fact}

*Automatically generated by GitHub Actions*
''')
        
        print(f"Generated fact: {fact}")
        print(f"Created file: {filename}")
        EOF
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add _posts/
        git commit -m "Add daily tech fact" || exit 0
        git push